name: Update Documentation

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - name: Install dependencies
          run: |
            pip install -U pip
            pip install -r requirements.txt
        - name: Sphinx Build
          run: |
            sphinx-build . _build
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          with:
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: _build
            force_orphan: true
            cname: docs.nelsondane.me
